### ISSUE TITLE
NPLdap is not working with Nprinting 17.3 version

### ISSUE THREAD

**Issue by Rchamarthi14** [expovin/NPLdapInport#1]
Hi,

I have followed the steps given in video and run the npm start command. I opened Http://localhost:3000 but it is getting me blank screen. Please help..

I have been trying this in N printing 17.3 version. does importer not compatible with 17.3

**Comment by expovin** [comment]
Hi, thanks for your feedback.
This extension works with NPrinting June Release 2017 version and beyond. This is because in the ver. 17.3 few APIs methods was just introduced as experimental part (not supported) and users end point was not part of them.
It was a lack in the readme file I just fixed.

Vincenzo
